name: CheckPayload

on:
  issues:
    types:
      - opened

jobs:
  debug:
    if: contains(github.event.label.name, '디버깅용_라벨')
    runs-on: ubuntu-latest
    steps:
      - name: Show event payload
        run: cat $GITHUB_EVENT_PATH

## 제이슨 형식으로 정리해서 볼 수 있음
