name: CheckPayload

on:
  issues:
    types:
      - labeled
    labels:
      - '동작 안시킬꺼임'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show event payload
        run: cat $GITHUB_EVENT_PATH
