name: CheckPayloadByDocs

on:
  issues:
    types:
      - opened

jobs:
  print_context:
    if: contains(github.event.label.name, '디버깅용_라벨')
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

## 제이슨 형식으로 정리 안되어서 나옴 -> 공식문서에 나오는 방식 그대로
