name: Branch Push Test

on:
  push:

# 실질적으로 특정브랜치에서 테스트할때 이렇게 구성함
# on:
#  push:
#    branches: [ "cd_temp_test" ]


jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch info
        run: |
          echo "특정 브랜치에서만 push 트리거 동작 테스트 입니다."
